# Generated by Django 5.1 on 2024-09-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_systemconfiguration_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_view_streams',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='has_full_access',
            field=models.BooleanField(default=False),
        ),
    ]
