# Generated by Django 5.1 on 2024-09-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_userrole_custom_can_view_streams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerafeed',
            name='is_streaming',
            field=models.BooleanField(default=False),
        ),
    ]
