# Generated by Django 5.1 on 2024-09-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('newapp', '0005_camerafeed_is_streaming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='can_view_streams',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_view_users',
        ),
        migrations.RemoveField(
            model_name='role',
            name='has_full_access',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='custom_can_view_streams',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='custom_can_view_users',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='custom_has_full_access',
        ),
        migrations.AlterField(
            model_name='camerafeed',
            name='feed_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
